spring.application.name=app

#Tun off the spring boot banner
spring.main.banner-mode=off

#Reduce logging level
logging.level.root=warn

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

application.security.jwt.access-token-expiration=900000
application.security.jwt.refresh-token-expiration=604800000

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

application.security.jwt.secret-key=${JWT_SECRET}